spring.application.name=employee-management


# originally
# spring.datasource.url=jdbc:mysql://localhost:3306/EmployeeManagement?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=laurence12345

# changed to
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/EmployeeManagement?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:laurence12345}

# notes: try to use environment variable if it exists.
# if environment variable is not set, use the default value after the colon :


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.defer-datasource-initialization=true





spring.security.user.name=admin
spring.security.user.password=123

