spring.application.name=employee-management



spring.datasource.url=jdbc:mysql://localhost:3306/EmployeeManagement?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=laurence12345


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true



spring.security.user.name=admin
spring.security.user.password=123

# for rendering pages
admin.login=/login
admin.dashboard=/admin/dashboard
admin.reports=/admin/reports

# for api calls
api.admin.path=/api/admin
api.admin.employee.add=/add-employee
api.admin.employee.edit=/edit-employee/{id}
api.admin.employee.delete=/delete-employee/{id}
api.admin.search=/search
api.admin.statistics=/statistics
api.admin.sort.department=/by-department
api.admin.sort.age=/by-age

# pagination defaults
pagination.default.page=0
pagination.default.size=5


